### ISSUE TITLE
Ask Permission to Take Some Template

### ISSUE THREAD

**Issue by ismailsunni** [luukvdmeer/msc-thesis#1]
Hi @luukvdmeer 

I am working on my master thesis also and I use thesisdown like yours. Since I am new in this stuff (Rmarkdown, thesisdown, and Latex), I would like to ask you for some template that you use (e.g. the Declaration of Academic Integrity and the approval).

I hope it's ok :)

**Comment by luukvdmeer** [comment]
Hi! You can use anything you want, no problem. I hope it is not too messy ;)

**Comment by ismailsunni** [comment]
Thanks @luukvdmeer !
